[package]
name = "HUD Weapon Charge"
description = "Adds a fillbar that shows the currently equipped weapon's charge under the weapon condition bar on the HUD"
homepage = "https://www.nexusmods.com/morrowind/mods/47962"
repository = "https://github.com/Virnetch/tes3-mods"
authors = ["Virnetch"]
version = "1.1.0"

[tools.mwse]
lua-mod = "Virnetch.HUDWeaponCharge"
wait-until-initialized = false
