[package]
name = "Customizable MWSE Multi Mark and Harder Recall"
description = "An overhaul of the mark and recall system"
homepage = "https://www.nexusmods.com/morrowind/mods/47065"
repository = "https://github.com/Virnetch/tes3-mods"
authors = ["Virnetch"]
version = "2.1.9"

[tools.mwse]
lua-mod = "Virnetch.multimark"
wait-until-initialized = false

[dependencies.mods."MagickaExpanded"]
mwse-module = "OperatorJack.MagickaExpanded.magickaExpanded"
url = "https://www.nexusmods.com/morrowind/mods/47111"
# version = ">=2.0.5"
