[package]
name = "Hotkeys Extended"
description = "Expands the vanilla Quick Menu by adding different hotkeys for holding or double tapping a button and/or when holding a specific button"
homepage = "https://www.nexusmods.com/morrowind/mods/48055"
repository = "https://github.com/Virnetch/tes3-mods"
authors = ["Virnetch"]
version = "1.1.3"

[tools.mwse]
lua-mod = "Virnetch.HotKeys"
wait-until-initialized = false
