[package]
name = "Protective Helmets"
description = "Automatically adds resistances to diseases and poisons when wearing a closed helmet"
homepage = "https://www.nexusmods.com/morrowind/mods/50280"
repository = "https://github.com/Virnetch/tes3-mods"
authors = ["Virnetch"]
version = "1.0.2"

[tools.mwse]
lua-mod = "Virnetch.protectiveHelmets"
wait-until-initialized = false
