name: Package

on:
  push:
    tags:
      - '*-v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create metadata.toml
        shell: bash
        run: ./metadata.sh

      - name: Package All
        run: |
          sudo apt-get install p7zip
          for dir in */
          do
            dir=${dir%*/}
            echo "Packaging $dir"
            mv "$dir/README.md" "$dir/$dir - README.md"
            7z a "${dir// /}.7z" "./$dir/*"
          done

      - name: Create Changelog
        id: create_changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1.15.0
        with:
          allowUpdates: true
          artifacts: "*.7z,metadata.toml"
          body: ${{ steps.create_changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge cache for camo images in README
        shell: bash
        run: |
          curl -s https://github.com/${{ github.repository }} |
            grep -oE "https://camo.githubusercontent.com[a-zA-Z0-9/]+" |
            sort -u |
            while read url; do
              curl -sX PURGE "$url";
              echo;
            done
